
# Site settings
title: Mixin Buttons
baseurl: "/mixin-buttons"
description: "SASS Mixins for generate beautiful buttons"
url: "http://nandomoreira.me"

# Build settings
markdown: kramdown

source: doc
destination: _site
sass:
  sass_dir: _sass
  style: compressed

jekyll-press:
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
  #js_options: {}      # js minifier options
