
# Site settings
title: Mix Buttons
baseurl: "/mix-buttons"
description: "SASS Mixins for generate beautiful buttons"
url: "http://nandomoreira.me"

# Build settings
markdown: kramdown
highlighter: pygments

gems:
  - jekyll-paginate
  - jekyll-gist

source: doc
destination: _site
sass:
  sass_dir: _sass
  style: compressed
